chore(QPT): ANA-1572 Add password as additional param to create-account
bigcommerce-labs/bc-functional-ui pull request #22
Opened 2020-09-15 19:19 UTC by avattipalli

Jira: [ANA-1752](https://jira.bigcommerce.com/browse/ANA-1752)

## What? Why?
Currently, we have hardcoded string as a password in create-account service. We want to remove that and require the service consumers to pass in the password as an additional parameter to email_address and account type.

This way service consumers generate and know their password and we don't have to send them back password or hardcode it or store them as secrets.

## How was it tested?
Updated current tests and ran them locally

- [ ] Cloud Dev end-to-end - Describe Steps
- [ ] Additional test cases (Optional)
- [ ] Integration - Describe Steps (Optional)

## Testing / Proof
...

## How can this be undone?
1. Revert this PR

ping @bigcommerce/billing-iam-testing

2020-09-15 19:40 UTC, j05h requested changes

2020-09-15 19:40 UTC, j05h commented on package.json
> +    "bc-store-setup-node": "github:bigcommerce-labs/bc-store-setup-node",
Nice, this is cleaner.

2020-09-15 19:40 UTC, j05h commented on test/services/create-account-test.js
> +      await createAccount('example@example.com', 'Password1!',  'non-trial');
We should also use `faker` here.

2020-09-15 19:40 UTC, j05h commented on test/services/create-account-test.js
> +    const res = await createAccount('example@example.com', 'Password1!', 'non-trial');
We should also use `faker` here.

2020-09-16 13:50 UTC, j05h approved these changes

2020-09-16 15:06 UTC, MarkJCram commented on src/services/create-account.js
> +      password: password,
Are we including the passed password as part of the logging/reporting?  Not a huge thing if we're going to creating a new account each time, but if we end up passing a static secret password this wouldn't be ideal

2020-09-16 15:10 UTC, avattipalli commented on src/services/create-account.js
> +      password: password,
Good catch! I was printing it on the logs as part of testing initially but we don't require that. I will remove it.

2020-09-16 15:37 UTC, MarkJCram commented on src/services/store-service.js
> +    console.log(`Login url: ${CP_HOST}`);
Good catch on this

2020-09-16 15:39 UTC, MarkJCram approved these changes

2020-09-16 15:44 UTC, merged