Fix: QE-208 Fix timeout failure in store-service
bigcommerce-labs/bc-functional-ui pull request #32
Opened 2020-10-01 18:42 UTC by avattipalli

Jira: [QE-208](https://jira.bigcommerce.com/browse/QE-208)

## What? Why?
In store-service we keep hitting the store provisioning service until it is fulfilled and then return the store details to the caller. In its current state, just happened to discover that the timeout actually never times out. This was noticed with one of my deployment of POC test where in the job never reached a finish state because store-provision took forever.

With this change, we are time boxing the timeout to approximately be about 1 minute. Let me know if that's too short.

If introducing a new structure or paradigm into the code or if adding a new helper or utility, use this as an opportunity to describe it.

## Affected areas?
Call out any changes that will impact, modify or alter the tests that will use the existing logic/codebase/domains.

For each affected area, indicate how your code will change it and how big the risk or impact is.

Do any of the tests needs to be updated potentially because of this change.

## Additional Deploy Steps? (Optional)
None

## How was it tested?

- [ ] Cloud Dev end-to-end - Describe Steps
- [ ] Additional test cases (Optional)
- [ ] Integration - Describe Steps (Optional)

## Testing / Proof
...

## How can this be undone?
1. Revert this PR

ping @bigcommerce/billing-iam-testing

2020-10-01 20:19 UTC, MarkJCram commented on test/functional/examples/store-provisioning-example-spec.js
> +    const password = `${faker.internet.password}_1!`;
If we're using faker for the rest, can't we use faker to produce numbers and special characters, as well?

2020-10-01 20:22 UTC, avattipalli commented on test/functional/examples/store-provisioning-example-spec.js
> +    const password = `${faker.internet.password}_1!`;
so `internet.password` does produce an alphanumeric string sometimes with special characters. I'm appending that special char at the end just so this doesn't cause A&A to fail being unable to create a user due to unmatched password complexity. Was that the answer you're looking for?

2020-10-01 20:24 UTC, MarkJCram commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
This is going to attempt to retry `getStore` 180 times?

2020-10-01 20:27 UTC, avattipalli commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
Ya, that's the max. Previously it was hitting it continuously until the response was a success. May be we should pause for about 3 seconds when it isn't successful and retry? That way we can limit hitting that service to may be 30 times which would approximately be for about 1 and a half minute waiting for store provisioning to complete.

2020-10-01 20:32 UTC, MarkJCram commented on test/functional/examples/store-provisioning-example-spec.js
> +    const password = `${faker.internet.password}_1!`;
I understand, I was thinking more along the lines of user faker to also generate random numbers and special characters (like with faker.random.number).  That might be beyond what we really need, though.

2020-10-01 20:33 UTC, MarkJCram commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
Yeah, I'd suggest even longer than 3 seconds to avoid us spamming the api and potentially getting rate limited

2020-10-01 20:34 UTC, avattipalli commented on test/functional/examples/store-provisioning-example-spec.js
> +    const password = `${faker.internet.password}_1!`;
Yeah, for now may be. Also, this is just an example spec so I don't really mind having anything just to serve the purpose.

2020-10-01 20:35 UTC, avattipalli commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
Cool. Will probably add a wait of 5 seconds before retry.

2020-10-01 20:39 UTC, MarkJCram commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
I'm also not 100% certain about the functionality of this...if there's an internal error and we're getting 500's returned, are we then going to attempt to hit the service 180 times?

2020-10-01 20:42 UTC, avattipalli commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
I am going to limit hitting the service to 20 times with each try after 5 seconds. If there was an error, it immediately breaks the loop because the `workflow_state` will no longer be **not fulfilled** but something else (which I assume).

2020-10-01 21:09 UTC, avattipalli commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
Added a timeout of 10 seconds before retrying to get store details again. Maximum tries is limited to 15 so the total wait before it fails will be 150 seconds or 2 minutes and 30 seconds. Please let me know how do we feel about this. I

2020-10-01 22:06 UTC, MarkJCram commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
That definitely seems much better!

2020-10-01 22:06 UTC, MarkJCram approved these changes

2020-10-02 14:18 UTC, j05h requested changes

2020-10-02 14:18 UTC, j05h commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
Ideally you would perform an exponential backoff here instead. Instead of only have a a `10s` delay, you could have a `1s` delay, then `2s`, `4s`, `8s`, `16s` etc up to some maximum. This will ensure you 

a) don't spam the servers
b) can actually run the tests in a reasonable amount of time

After 5-6 iterations of this, I'd stop, if it doesn't respond within `32s` or so, it won't. Going to `32s` would be a total delay of `63s` seconds, but you'd make the first few hits much more quickly. In an exponential backoff, you'd have done 4 hits of the API in the same time you do 2 with your current constant model.

2020-10-02 14:18 UTC, j05h commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
Not sure why you are still adding `RETRY_TIME` here, you're using `retry` as a counter, if that's the case, you should have a hard coded `1` here instead of using a `const`.

2020-10-02 14:53 UTC, avattipalli commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
I thought about this and here's the first hand information I have. Most of the times, the provisioning response comes in between `20-30 seconds`. I don't remember getting a response within the first 10 seconds anytime. The earliest was somewhere in between `10-20 seconds`. 

So, if I go with exponential timeout, the maximum number of hits happen at the beginning and the store provisioning wouldn't have completed. An inverse of an exponential counter may also run into a scenario of spamming the server if we do not have a response after the first few trials. That made me go for a constant wait between retries.

2020-10-02 14:54 UTC, avattipalli commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
Ya, not sure what I was thinking. What you said makes sense.

2020-10-02 16:12 UTC, avattipalli commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
I also looked up on BC-App to see how they are handling this

https://github.com/bigcommerce/bigcommerce/blob/4e3d404286eda2f34a9e2fcc921479cc499d7d38/tests/Functional/BMPStoreBootstrap.php#L210

They seem to be doing the retry 30 times every 5 seconds so what we are doing here doesn't seem bad. Also, there's lot more traffic there which the service seems to handle pretty well.

2020-10-02 16:18 UTC, j05h commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
Mm...I see, the endpoint is slow anyway... So, I think really want you want to do is wait ...  `10s` and then progressively add a smaller amount to that. Like `10s`, `5s`, `3s` ... down to a minimum (and maybe that minimum is `3s`. Just seems like `10s` is a long time to be your interval.

2020-10-02 16:19 UTC, j05h commented on src/services/store-service.js
>              retry += API_RETRY_TIME;
Also, you're really making a `for` loop here... You may as well make it that.

2020-10-05 15:32 UTC, j05h requested changes

2020-10-05 15:32 UTC, j05h commented on src/services/store-service.js
> +    } while (provisioningResponse.data.workflow_state !== 'fulfilled' );
I think you can simplify this with a single `do...while` loop.

```javascript
let delay = 10;
let startTime = new Date();
do {
   await new Promise(r => setTimeout(r, delay * 1000));
   provisioningResponse = await getStore(requestId, account);
   if(delay > 1)
      delay--;
   if((new Date() - startTime) / 1000 > STORE_CREATION_TIMEOUT){
            const errorMessage = `Provisioning failed to create store within ${STORE_CREATION_TIMEOUT} seconds`;
            console.log(errorMessage);
            throw errorMessage;
   }
} while (provisioningResponse.data.worflow_state !== 'fulfilled');

2020-10-05 15:47 UTC, avattipalli commented on src/services/store-service.js
> +    } while (provisioningResponse.data.workflow_state !== 'fulfilled' );
This will try for 10 times decrementing rate for about 55 seconds, before throwing the error. I think that's a short timeout so I had it hit the service with a gap of 7 seconds to 3 seconds and retry it for 5 times which will try for approximately 2 mins.  

I don't mind going with the above logic and give it a shot. If in the future we deduce that the timeout is short (we are still in the POC phase so we can try a few things), we can change the above logic and fallback to the approach I've taken. Please let me know how you feel about it.

2020-10-05 18:55 UTC, j05h commented on src/services/store-service.js
> +    } while (provisioningResponse.data.workflow_state !== 'fulfilled' );
I'm just thinking something simpler and more readable would be good. You could even do something where you start with 10000 and decrement from that so you get more iterations before its fast? It may even make sense to encapsulate parts of it in methods to clean up the logic, that nesting makes things harder to understand.

2020-10-05 18:57 UTC, j05h commented on src/services/store-service.js
> +    } while (provisioningResponse.data.workflow_state !== 'fulfilled' );
Also, this should run for the full 120 seconds as it doesn't error until then. It just has a minimum delay of 1 second. So after waiting during the downdown with each delay getting progressively smaller, it bottoms out.

2020-10-05 19:06 UTC, avattipalli commented on src/services/store-service.js
> +    } while (provisioningResponse.data.workflow_state !== 'fulfilled' );
Cool, I'm going to clean this up and try making it look better.

2020-10-05 19:45 UTC, avattipalli commented on src/services/store-service.js
> +    } while (provisioningResponse.data.workflow_state !== 'fulfilled' );
I previously didn't read this line `if((new Date() - startTime) / 1000 > STORE_CREATION_TIMEOUT)` correctly, hence I understood it incorrectly to timeout less than a minute.

Preserved your logic as that looks cleaner and moved out all the log statements to its own method. Hope this looks better.

2020-10-05 21:44 UTC, j05h approved these changes
Approving, though there is a little 🍺 in there...

2020-10-05 21:44 UTC, j05h commented on src/services/store-service.js
> +        if (delay > 1)
Lets make the `1` a constant `MINIMUM_DELAY` so its a bit more obvious.

2020-10-05 21:44 UTC, j05h commented on src/services/store-service.js
> +let delay = 10;
Lets make the `10` a `MAXIUMUM_DELAY` constant as well.

2020-10-05 22:25 UTC, avattipalli commented
Waiting until the failing functional specs is resolved to merge this. Nothing to do ATM from our end, just integration playing stuff.

2020-10-06 14:41 UTC, merged