QE-209: Add experiments service
bigcommerce-labs/bc-functional-ui pull request #34
Opened 2020-10-07 17:41 UTC by avattipalli

Jira: [QE-209](https://jira.bigcommerce.com/browse/QE-209)

## What? Why?
We require experiment service setup for successfully testing features behind experiments. This will help functional tests that want to verify the behavior while they're still not fully enabled to the end user.

## How was it tested?

- [ ] Cloud Dev end-to-end - Describe Steps
- [x] Additional test cases (Optional)
- [ ] Integration - Describe Steps (Optional)

## Testing / Proof
...

## How can this be undone?
1. Revert this PR

ping @bigcommerce/billing-iam-testing

2020-10-12 15:57 UTC, avattipalli commented on package.json
> +    "axios": "^0.20.0",
Added axios as we decided to write our services independent of codeceptjs and so can test them by having unit tests.

2020-10-12 20:50 UTC, j05h requested changes

2020-10-12 20:50 UTC, j05h commented on src/services/experiment-service.js
> +            return await _getExperimentPercent(url, account, experimentID);
It will be cleaner to change this method to take an optional `retries` parameter which defaults to your max. The way you have it would be problematic for parallelization because multiple threads might access `RETRY_LIMIT`

```suggestion
            if (retries < 1) {
                _logMessage(`Failed to retrieve config percent for experiment ${experimentID}`);
                throw error;
            }
            await new Promise(r => setTimeout(r, 3000));
            retries--;
            return await _getExperimentPercent(url, account, experimentID, retries);
```

2020-10-12 20:50 UTC, j05h commented on src/services/experiment-service.js
> +    const url = `${storeURL}${EXPERIMENT_ENDPOINT}?key=${experimentID}`;
Its better to construct these to avoid any input errors. For example, the `URL` constructor will fix issues with double `/` in your pathing.

```suggestion
    const url = new URL(EXPERIMENT_ENDPOINT, storeUrl);;
    url.searchParams.append('key', experimentID);
```

When you want to use it, you could call `url.toString()`.

2020-10-12 20:50 UTC, j05h commented on src/services/experiment-service.js
> +    const url = `${storeURL}${EXPERIMENT_ENDPOINT}?key=${experimentID}`;
See the note on `URL` instantiation below.

2020-10-12 20:57 UTC, avattipalli commented on src/services/experiment-service.js
> +    const url = `${storeURL}${EXPERIMENT_ENDPOINT}?key=${experimentID}`;
Didn't know about this. Will update it!

2020-10-12 21:09 UTC, j05h commented on src/services/experiment-service.js
> +    const url = `${storeURL}${EXPERIMENT_ENDPOINT}?key=${experimentID}`;
Most languages have something similar. I try to use them as much as possibly simply because it'll save your butt at some point.

2020-10-13 20:40 UTC, j05h approved these changes
One small change, but LGTM

2020-10-13 20:40 UTC, j05h commented on src/services/experiment-service.js
> +    retries = retries || 10;
```suggestion
async function _getExperimentPercent(storeURL, account, experimentID, retries = 10) {
```

2020-10-14 14:56 UTC, merged